app/urls.py
from django.urls import path
from app.views import * 
app_name='app'

urlpatterns=[

    path('radheshyam/',radheshyam,name='radheshyam'),
]

app1/urls.py
from django.urls import path
from app1.views import * 
app_name='app1'

urlpatterns=[
    path('adipurush/',adipurush,name='adipurush'),
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app1
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app1/',include('app1.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.

def radheshyam(request):
    return render(request,'radheshyam.html')

app1/views.py
from django.shortcuts import render

# Create your views here.

def adipurush(request):
    return render(request, 'adipurush.html')

templates/adipurush.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: rgb(71, 5, 40);">
    <center>
        <h1 style="color: aquamarine;">Adipurush_page</h1>

        <marquee behavior="" direction=""><h1 style="color: burlywood;">Jai Sree Ram</h1></marquee>
        <h1>Here we Used Specific_url_Navigation</h1>
        <h1><a href="{% url 'app:radheshyam' %}">Radheshyam</a></h1>
    </center>
</body>
</html>

templates/radheshyam.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: darkorange;">
    <center>
        <h1 style="color: rgb(237, 228, 234);">Radheshyam_page</h1>
       <marquee behavior="" direction=""><h1 style="color: rgb(16, 12, 0);">Here we Used Specific_url_Navigation</h1></marquee>
       <h1><a href="{%url 'app1:adipurush'%}">Adipurush</a></h1>
    </center>
   
    
</body>
</html>